#!/usr/bin/env python
#coding=utf-8

META = ["idOsobyPuvodce", "druhStavRizeni", "nazevOsoby", "idOsoby", "idOsoby1", "idOsoby2", "idOsoby3",
        "druhRoleVRizeni", "druhOsoby", "jmeno", "rc", "datumPobytOd",
        "adresa", "psc", "mesto", "idAdresy", "cisloPopisne", "ulice",
        "datumNarozeni", "ic", "druhPravniForma", "titulPred", "okres", "zeme",
        "druhSpravce", "nazevOsobyObchodni", "priznakAnInterniCisUdalost",
        "popisCisUdalosti", "datumZalozeniCisUdalosti", "cisUdalost",
        "telefon", "fax", "datumZruseniCisUdalosti", "priznakAnVedlejsiUdalost",
        "priznakAnVedlejsiDokument", "datumPravniMoci", "bcVecHlavni",
        "druhVecHlavni", "rocnikHlavni", "datumSpojeni", "priznakMylnyZapisVeritelPohled",
        "priznakPlatnyVeritel", "datumOddeleni", "datumZverejneniOpraveneUdalosti",
        "datumOsobaVeVeciZrusena", "titulZa", "dic", "datumUstanoveniSpravce"]

KODY = {
    1: "Změna osoby",
    2: "Změna adresy osoby",
    4: "Změna v číselníku událostí",
    5: "Insolvenční návrh",
    6: "Insolvenční návrh spojený s návrhem na povolení oddlužení",
    7: "Insolvenční návrh spojený s návrhem na povolení reorganizace",
    8: "Návrh",
    9: "Návrh na předběžné opatření",
    10: "Návrh na moratorium",
    11: "Návrh na zrušení moratoria",
    12: "Návrh na vynětí majetku z majetkové podstaty",
    13: "Návrh na povolení reorganizace",
    16: "Návrh změny reorganizačního plánu",
    17: "Návrh na přeměnu reorganizace v konkurs",
    18: "Návrh na povolení oddlužení",
    19: "Návrh na osvobození od placení dosud neuspokojených pohledávek",
    20: "Návrh na zrušení schváleného oddlužení",
    21: "Návrh - zpětvzetí",
    22: "Návrh - doplnění návrhu",
    23: "Návrh - přílohy",
    24: "Námitky",
    25: "Námitky proti konečné zprávě",
    26: "Námitky proti povolení oddlužení dle § 403 odst. 2",
    27: "Žaloba",
    28: "Sdělení",
    29: "Sdělení dlužníka",
    30: "Sdělení věřitele",
    31: "Sdělení známého věřitele o pohledávce",
    32: "Sdělení finančního úřadu",
    33: "Sdělení banky",
    34: "Sdělení živnostenského úřadu",
    35: "Sdělení Ministerstva vnitra (auta)",
    36: "Sdělení Střediska cenných papírů",
    37: "Sdělení Katastru nemovitostí",
    38: "Sdělení dlužníka o nepředložení reorganizačního plánu",
    39: "Sdělení správce o plnění oddlužení",
    40: "Sdělení dlužníka o plnění oddlužení",
    41: "Vyjádření",
    42: "Vyjádření dlužníka",
    43: "Vyjádření navrhovatele",
    44: "Dotaz na stav řízení",
    45: "Stížnost",
    46: "Stížnost dlužníka",
    47: "Stížnost věřitele",
    48: "Zpráva",
    49: "Zpráva o hospodářské situaci dlužníka",
    50: "Zpráva o průběhu zpeněžení",
    51: "Zpráva o plnění reorganizačního plánu",
    52: "Zpráva dlužníka o svých příjmech dle § 412 odst. 1 písm. d)",
    53: "Zpráva dlužníka o změně údajů dle § 412 odst. 1 písm. c)",
    54: "Znalecký posudek",
    55: "Plná moc",
    56: "Výpis",
    58: "Výpis z obchodního rejstříku",
    59: "Reorganizační plán",
    60: "Reorganizační plán - zpráva",
    61: "Jiné podání",
    62: "Hlasovací lístek",
    63: "Přihláška pohledávky",
    64: "Seznam přihlášených pohledávek",
    65: "Seznam přihlášených pohledávek - výpis",
    66: "Usnesení",
    67: "Usnesení o vyhlášení moratoria",
    68: "Usnesení o odmítnutí návrhu na moratorium",
    69: "Usnesení o prodloužení moratoria",
    70: "Usnesení o zrušení moratoria",
    71: "Usnesení o nevyhovění návrhu na zrušení moratoria",
    72: "Usnesení o odmítnutí insolvenčního návrhu",
    73: "Usnesení o zastavení řízení pro zpětvzetí insolvenčního návrhu",
    74: "Usnesení o neúčinnosti zpětvzetí insolvenčního návrhu",
    75: "Usnesení o úpadku",
    76: "Usnesení o úpadku spojené s prohlášením konkursu",
    77: "Usnesení o úpadku spojené s povolením reorganizace",
    78: "Usnesení o úpadku spojené s povolením oddlužení",
    79: "Usnesení o způsobu řešení úpadku konkursem dle usnesení schůze věřitelů",
    80: "Usnesení o způsobu řešení úpadku reorganizací dle usnesení schůze věřitelů",
    81: "Usnesení o zastavení řízení pro nedostatek podmínky řízení",
    82: "Usnesení o zamítnutí insolvenčního návrhu",
    83: "Usnesení o zamítnutí insolvenčního návrhu pro nedostatek majetku dlužníka",
    84: "Usnesení o tom, že dlužník není v úpadku",
    85: "Usnesení o vydání předběžného opatření",
    86: "Usnesení o zrušení předběžného opatření",
    87: "Usnesení o zastavení řízení pro nezaplacení zálohy na náklady řízení",
    88: "Usnesení o ustanovení předběžného správce",
    89: "Usnesení o záloze na náklady předběžného správce",
    90: "Usnesení o hotových výdajích a odměně předběžného správce",
    91: "Usnesení o ustanovení znalce",
    92: "Usnesení o schválení odměny znalce",
    94: "Usnesení o prohlášení konkursu",
    95: "Usnesení o zrušení konkursu",
    96: "Usnesení o schválení zprávy správce po úmrtí dlužníka",
    97: "Usnesení o nepatrném konkursu",
    98: "Usnesení o zrušení rozhodnutí o nepatrném konkursu",
    99: "Usnesení o povolení reorganizace",
    103: "Usnesení o zastavení řízení o žalobě",
    104: "Usnesení o smíru",
    105: "Usnesení o ustanovení správce",
    106: "Usnesení o potvrzení správce zvoleného schůzí věřitelů",
    107: "Usnesení o nepotvrzení správce zvoleného schůzí věřitelů",
    108: "Usnesení o odvolání správce z funkce",
    109: "Usnesení o zproštění funkce správce pro porušení povinností",
    110: "Usnesení o zproštění funkce správce po skončení řízení",
    112: "Usnesení o rozsahu hlasovacího práva na schůzi věřitelů",
    113: "Usnesení o zrušení usnesení schůze věřitelů",
    114: "Usnesení o zamítnutí návrhu na zrušení usnesení schůze věřitelů",
    115: "Usnesení o potvrzení volby členů a náhradníků věřitelského orgánu",
    116: "Usnesení o jmenování prozatímního věřitelského výboru",
    117: "Usnesení o jmenování členů a náhradníků věřitelského výboru",
    118: "Usnesení o odměně a náhradě nutných výdajů likvidátora",
    119: "Usnesení o odvolání z funkce člena nebo náhradníka věřitelského výboru",
    120: "Usnesení o změně věřitelského orgánu v souvislosti s postupem pohledávky",
    121: "Usnesení o odvolání věřitelského výboru",
    122: "Usnesení o uložení pořádkové pokuty",
    123: "Usnesení o předvolání k výslechu",
    124: "Usnesení o odmítnutí přihlášky",
    125: "Usnesení o tom, že se k přihlášce nepřihlíží",
    126: "Usnesení o vzetí na vědomí zpětvzetí přihlášky",
    128: "Usnesení o ukončení účasti věřitele v insolvenčním řízení",
    129: "Usnesení o opatřeních potřebných k zjištění majetkové podstaty a způsobu zjištění",
    131: "Usnesení o upuštění od provedení soupisu majetku",
    132: "Usnesení o stanovení lhůty pro splnění pohledávky za podstatou a určení části majetkové podstaty, která bude k úhradě použita",
    134: "Usnesení o vynětí majetku z majetkové podstaty",
    135: "Usnesení o neúčinnosti právního úkonu",
    136: "Usnesení o neplatnosti právního úkonu",
    137: "Usnesení o vyhovění návrhu nájemce na zrušení výpovědi nájemní smlouvy"  ,
    138: "Usnesení o skončení provozu dlužníkova podniku",
    139: "Usnesení o pokračování v přerušeném řízení",
    141: "Usnesení o schválení dohody o vypořádání SJM",
    142: "Usnesení o zrušení rozhodnutí o schválení dohody o vypořádání SJM",
    144: "Usnesení o opatření k vynucení splnění uložených povinností",
    145: "Usnesení o prodloužení lhůty ke splnění povinností",
    146: "Usnesení o povolení výjimky ze zákazu nabývání majetku z majetkové podstaty",
    147: "Usnesení o pořadí úhrady pohledávky",
    148: "Usnesení o povolení částečného rozvrhu",
    149: "Usnesení o konečné zprávě",
    150: "Usnesení o zákazu nakládat s majetkovou podstatou",
    151: "Usnesení o omezení nakládat s majetkovou podstatou",
    152: "Usnesení o odmítnutí návrhu na povolení reorganizace pro opožděnost",
    153: "Usnesení o odmítnutí návrhu na povolení reorganizace pro vady",
    154: "Usnesení o vzetí na vědomí zpětvzetí návrhu na povolení reorganizace",
    156: "Usnesení o zamítnutí návrhu na povolení reorganizace",
    158: "Usnesení o schválení reorganizačního plánu",
    159: "Usnesení o schválení změny reorganizačního plánu",
    160: "Usnesení o neschválení změny reorganizačního plánu",
    161: "Usnesení o zamítnutí reorganizačního plánu",
    163: "Usnesení o přeměně reorganizace v konkurs",
    164: "Usnesení o vzetí na vědomí splnění reorganizačního plánu",
    165: "Usnesení o odměně správce",
    166: "Usnesení o zastavení řízení dle § 427",
    167: "Usnesení o odmítnutí návrhu na povolení oddlužení pro vady",
    168: "Usnesení o odmítnutí návrhu na povolení oddlužení pro opožděnost nebo neoprávněnost",
    169: "Usnesení o vzetí na vědomí zpětvzetí návrhu na povolení oddlužení",
    170: "Usnesení o neúčinnosti zpětvzetí návrhu na povolení oddlužení",
    171: "Usnesení o zamítnutí návrhu na povolení oddlužení",
    172: "Usnesení o povolení oddlužení",
    173: "Usnesení o způsobu oddlužení dle § 402 odst. 5",
    174: "Usnesení o schválení oddlužení zpeněžením majetkové podstaty",
    175: "Usnesení o schválení oddlužení plněním splátkového kalendáře",
    176: "Usnesení o neschválení oddlužení",
    177: "Usnesení o vzetí na vědomí splnění oddlužení",
    178: "Usnesení o osvobození dlužníka od placení dosud neuspokojených pohledávek",
    179: "Usnesení o odejmutí osvobození od placení dosud neuspokojených pohledávek",
    180: "Usnesení o zániku osvobození dlužníka od placení dosud neuspokojených pohledávek",
    181: "Usnesení o zrušení schváleného oddlužení",
    182: "Dotaz",
    183: "Rozsudek",
    184: "Vyhláška",
    185: "Vyhláška o zahájení insolvenčního řízení",
    186: "Vyhláška o svolání schůze věřitelů",
    187: "Vyhláška o svolání přezkumného jednání",
    188: "Vyhláška o konečné zprávě",
    189: "Výzva",
    190: "Usnesení o uložení povinnosti zaplatit zálohu",
    191: "Výzva věřitelům k podávání přihlášek pohledávek",
    192: "Výzva na doplnění příloh insolvenčního návrhu",
    193: "Výzva na předložení seznamů k insolvenčnímu návrhu",
    194: "Výzva dlužníkovi k vyjádření se k insolvenčnímu návrhu",
    195: "Výzva na správce",
    196: "Výzva na odstranění vad návrhu na vynětí majetku",
    197: "Výzva k opravě nebo doplnění návrhu na povolení reorganizace",
    198: "Výzva k předložení reorganizačního plánu",
    199: "Výzva k opravě nebo doplnění návrhu na povolení oddlužení",
    200: "Výzva na zprávu správce o plnění oddlužení",
    201: "Výzva na zprávu dlužníka o plnění oddlužení",
    202: "Výzva k opravě nebo doplnění návrhu",
    203: "Výzva na podání žaloby dle § 100 odst. 2",
    204: "Pokyn insolvenčního soudu",
    205: "Souhlas",
    210: "Vyrozumění",
    211: "Vyrozumění ČNB o prohlášení konkursu",
    212: "Protokol",
    213: "Protokol o prohlášení o postoupení pohledávky",
    214: "Protokol ze schůze věřitelů",
    215: "Protokol o jednání",
    217: "Protokol o prohlášení o majetku",
    218: "Rozvrhové usnesení",
    219: "Předkládací zpráva",
    220: "Svolání",
    222: "Nařízení jednání",
    223: "Úřední záznam",
    224: "Záznam o nahlédnutí do spisu",
    226: "Konečná zpráva",
    227: "Opatření",
    228: "Opatření o určení osoby správce",
    230: "Odvolání",
    231: "Odvolání - doplnění",
    232: "Odvolání - zpětvzetí odvolání",
    233: "Vrácení spisu",
    234: "Zapůjčení spisu",
    236: "Záznam o nahlížení do spisu",
    237: "Vrácení spisu soudu I. stupně",
    238: "Mylný zápis",
    239: "Jiné",
    241: "Výzva",
    242: "Výzva na doplnění odvolání",
    243: "Výzva k vyjádření se k odvolání",
    245: "Usnesení na doplnění odvolání",
    246: "Usnesení k vyjádření se k odvolání",
    247: "Usnesení o změně v osobě věřitele",
    311: "Rozhodnutí o odvolání ve věci zproštění funkce insolv. správce, jeho výdajích a způsob úhrady - jiné",
    328: "Rozhodnutí opravné usnesení",
    329: "Záznam o mylném zařazení",
    330: "Změna XSD dokumentu poznámky",
    331: "Náhradní doručení",
    332: "Zpráva IS o stavu řízení",
    333: "Dohoda o vypořádání SJM",
    334: "Soupis majetkové podstaty",
    335: "Dražební vyhláška",
    336: "Protokol o vydražení",
    337: "List vlastnictví",
    338: "Návrh rozvrhového usnesení",
    339: "Návrh na schválení dohody o vypořádání SJM",
    340: "Návrh na svolání schůze věřitelů",
    341: "Návrh částečného rozvrhového usnesení",
    342: "Návrh na vydání opravného usnesení",
    343: "Návrh na změnu v osobě věřitele",
    344: "Návrh na zrušení konkurzu",
    345: "Návrh na zrušení předběžného opatření",
    346: "Návrh na vydání výtěžku zpeněžení zajištěnému věřiteli",
    347: "Návrh na vydání souhlasu se zpeněžením MP mimo dražbu",
    348: "Omluva",
    349: "Zpráva IS o splnění rozvrhového usnesení",
    350: "Zpráva IS po zrušení konkursu",
    351: "Platební poukaz",
    353: "Záznam o složení peněz do soudní úschovy",
    354: "Pověření asistenta soudce",
    355: "Pověření vyššího soudního úředníka",
    356: "Prezenční listina",
    357: "Přípis",
    358: "Sdělení o vstupu KSZ do řízení",
    359: "Vstup státního zastupitelství do řízení",
    360: "Výstupu státního zastupitelství z řízení",
    362: "Usnesení o ustanovení tlumočníka",
    363: "Vyúčtování odměny znalce nebo tlumočníka",
    365: "Výzva k zaplacení SOP",
    366: "Zaplacení SOP",
    367: "Žádost",
    368: "Náhradní doručení",
    369: "Právní moc",
    370: "Právní moc konečného rozhodnutí",
    371: "Informační zpráva",
    372: "Změna stavu věci",
    373: "Rozhodnutí o odvolání - potvrzeno",
    374: "Rozhodnutí o odvolání - změněno",
    375: "Rozhodnutí o odvolání - zrušeno a vráceno",
    376: "Rozhodnutí o odvolání - zastavení řízení",
    377: "Rozhodnutí o odvolání - odmítnuto",
    378: "Rozhodnutí o odvolání - jinak",
    380: "Zaslání rozhodnutí odvolacího soudu",
    381: "Zaslání rozhodnutí odvolacího soudu a vrácení spisu",
    382: "Převzetí věci Vrchním soudem",
    383: "Rozhodnutí o tom, zda je soudce vyloučen",
    384: "Rozhodnutí o delegaci",
    386: "Protokol o hlasování",
    387: "Žádost o zapůjčení spisu",
    388: "Příprava jednání",
    389: "Protokol o vyhlášení rozhodnutí",
    390: "Předložení věci Nejvyššímu soudu",
    391: "Rozhodnutí VS/NS o určení příslušnosti",
    392: "Předložení věci vrchnímu soudu",
    393: "Přípis - bez věcného vyřízení",
    399: "Rozhodnutí o dovolání - zrušeno a vráceno soudu 1. stupně",
    402: "Zaslání rozhodnutí dovolacího soudu a vrácení spisu",
    403: "Rozhodnutí o místní příslušnosti (§ 11 odst. 3 OSŘ)",
    404: "Převzetí věci Nejvyšším soudem",
    405: "Změna senátu věci",
    406: "Doručení do ciziny",
    407: "Dovolání",
    408: "Dovolání - doplnění dovolání",
    409: "Dovolání - zpětvzetí dovolání",
    410: "Insolvenční návrh spojený s návrhem na prohlášení konkursu",
    411: "Námitka podjatosti",
    412: "Námitky dle § 373 IZ",
    413: "Přihláška - návrh na vstup nového věřitele",
    414: "Návrh dlužníka",
    415: "Návrh na odvolání správce",
    416: "Návrh na odvolání z funkce ve v.v.",
    417: "Návrh na pokračování v řízení",
    418: "Návrh na rozhodnutí o hlasovacím právu",
    419: "Návrh na úpravu seznamu přihlášených pohledávek",
    420: "Návrh na uspokojení pohledávky za podstatou",
    421: "Návrh na uspokojení zajištěného věřitele",
    422: "Návrh na změnu předběžného opatření",
    423: "Návrh na zproštění správce z funkce",
    424: "Návrh veřitelského výboru",
    425: "Odvolání jiné",
    426: "Omluva",
    427: "Oznámení",
    428: "Oznámení soudu",
    429: "Oznámení o změně konání jednání",
    430: "Platební poukaz",
    431: "Pokračování v řízení po zpětvzetí",
    432: "Protokol z jednání věřitelského výboru",
    434: "Předvolání k výslechu",
    435: "Předvedení k soudu",
    436: "Převedení spisu příslušnému soudu",
    437: "Předvolání ke slyšení",
    438: "Převzetí spisu z jiného soudu",
    439: "Přezkumné jednání",
    440: "Přihláška pohledávky - částečné zpětvzetí",
    441: "Přihláška pohledávky - doplnění, oprava",
    442: "Přihláška pohledávky - zpětvzetí",
    443: "Příloha k protokolu o jednání",
    444: "Přistoupení k řízení (§ 107 IZ)",
    445: "Referát",
    446: "Referát pro judikaturu",
    447: "Sdělení o odstoupení z funkce ve v.v.",
    448: "Sdělení o osobě jednající jménem člena/náhradníka v.o.",
    449: "Seznam přihlášených pohledávek - změna",
    450: "Seznam/upravený seznam přihlášených pohledávek",
    451: "Schůze věřitelů",
    452: "Souhlas s určením zastupující osoby",
    453: "Soupis majetkové podstaty",
    454: "Soupis majetkové podstaty - doplnění",
    455: "Usnesení o nepotvrzení volby v.v.",
    456: "Usnesení o uspokojení pohledávky za podstatou",
    457: "Usnesení o doplnění/změně konečné zprávy",
    458: "Usnesení o nařízení předběžného opatření bez návrhu",
    460: "Usnesení o neschválení dohody o vypořádání SJM",
    461: "Usnesení o odměně a hotových výdajích tlumočníka",
    462: "Usnesení o odmítnutí konečné zprávy",
    463: "Usnesení o odmítnutí návrhu na předběžné opatření",
    464: "Usnesení o postoupení věci",
    465: "Usnesení o prominutí pořádkové pokuty",
    466: "Usnesení o schválení konečné zprávy",
    467: "Usnesení o ukončení lhůty k předložení reorganizačního plánu",
    468: "Usnesení o uložení povinnosti",
    469: "Usnesení o vyloučení z rozvrhu",
    470: "Usnesení o vyplacení zálohy na odměnu správce",
    471: "Usnesení o zamítnutí návrhu na předběžné opatření",
    472: "Usnesení o zániku pohledávky",
    473: "Usnesení o zastavení řízení",
    474: "Usnesení o zastavení řízení o předběžném opatření",
    475: "Usnesení o zastavení řízení vůči učastníku (§ 130 odst. 2 IZ)",
    476: "Usnesení o změně v osobě znalce",
    477: "Usnesení o změně rozhodnutí soudu I.stupně",
    478: "Usnesení o zrušení rozhodnutí soudu I.stupně",
    479: "Usnesení o uplynutí lhůty",
    480: "Vrácená obálka",
    481: "Vrácení příloh",
    482: "Vyhláška o hlasování",
    483: "Vyhláška o jednání o konečné zprávě",
    484: "Vyhláška o svolání zvláštního přezkumného jednání",
    485: "Výpis z evidence ARES",
    486: "Vyrozumění o soupisu majetkové podstaty",
    487: "Vyřízeno jiným způsobem",
    488: "Vyúčtování odměny a výdajů správce",
    489: "Výzva k odstranění odlišnosti návrhů",
    490: "Vzdání se práva odvolání",
    491: "Zahraniční insolvenční správce",
    492: "Zápis v rejstříku ukončen",
    493: "Zaslání doplnění přihlášky správci",
    494: "Zaslání přihlášky/přihlášek správci",
    495: "Záznam o složení zálohy",
    496: "Záznam o zaplacení zálohy na insolvenční řízení",
    497: "Zkrácené znění usnesení",
    498: "Zpětvzetí popření pohledávky insolvenčním správcem",
    499: "Zvláštní přezkumné jednání",
    501: "Žádost o určení osoby správce",
    502: "Rozhodnutí o odvolání - potvrzeno",
    503: "Rozhodnutí o odvolání - změněno",
    504: "Rozhodnutí o odvolání - zrušeno a vráceno",
    506: "Rozhodnutí o odvolání - odmítnuto",
    507: "Rozhodnutí o odvolání - jinak",
    508: "Zaslání rozhodnutí odvolacího soudu",
    510: "Převzetí věci vrchním soudem",
    511: "Rozhodnutí NS o dovolání - zastavení řízení",
    512: "Rozhodnutí NS o dovolání - odmítnutí",
    513: "Rozhodnutí NS o dovolání - zamítnutí",
    514: "Rozhodnutí NS o dovolání - zrušení a vrácení odvolacímu soudu",
    515: "Rozhodnutí NS o dovolání - zrušení a vrácení soudu 1. stupně",
    517: "Rozhodnutí NS o dovolání - jinak",
    524: "Protokol o hlasování",
    525: "Žádost o zapůjčení spisu",
    528: "Rozhodnutí o místní příslušnosti",
    529: "Zpětvzetí návrhu",
    530: "Návrh reorganizačního plánu",
    531: "Protokol o prohlídce prostor",
    532: "Opravné usnesení",
    533: "Sdělení Ministerstva vnitra (auta)",
    534: "Výpis ze seznamu přihlášených pohledávek",
    535: "Usnesení o prodeji mimo dražbu",
    536: "Usnesení o zpěněžení podniku",
    537: "Usnesení o uspokojení zajištěného věřitele",
    538: "Soupis majetkové podstaty - změna",
    539: "Usnesení o svolání věřitelského výboru",
    540: "Usnesení o nařízení prohlídky prostor",
    541: "Rozhodnutí jiného soudu",
    542: "Usnesení o odmítnutí žaloby",
    543: "Usnesení, kterým se věřiteli ukládá, aby plnil ve prospěch majetkové podstaty dle § 178 nebo § 179",
    544: "Výzva k podávání přihlášek pohledávek",
    545: "Vyhláška o výzvě k podávání přihlášek pohledávek",
    546: "Návrh na moratorium k insolvenčnímu návrhu",
    547: "Usnesení o vyhlášení moratoria - po insolvenčním návrhu",
    548: "Zánik moratoria",
    549: "Zánik moratoria - po insolvenčním návrhu",
    550: "Usnesení o zrušení moratoria - po insolvenčním návrhu",
    551: "Návrh na prodloužení moratoria",
    552: "Usnesení o změně rozhodnutí soudu I.stupně (bez změny stavu)",
    553: "Usnesení o zrušení rozhodnutí soudu I.stupně (bez změny stavu)",
    554: "Opětovné doručení vyhláškou",
    555: "Usnesení o změně insolvenčního správce",
    556: "Reklamace doručenky",
    557: "Usnesení o prodloužení moratoria",
    558: "Usnesení o prodloužení moratoria - po insolvenčním návrhu",
    559: "Usnesení o odmítnutí návrhu na moratorium - po insolvenčním návrhu",
    560: "Rozhodnutí o důvodnosti postoupení",
    561: "Konečný/Závěrečný referát",
    562: "Částečné zpětvzetí přihlášené pohledávky",
    563: "Doplnění/oprava/změna přihlášené pohledávky",
    564: "Odpověď na reklamaci doručenky",
    565: "Odročení jednání",
    566: "Odvolání do předběžného opatření",
    567: "Odvolání jednání",
    568: "Protokol z přezkumného jednání",
    569: "Protokol ze zvláštního přezkumného jednání",
    570: "Předložení přihlášky NS",
    571: "Předložení přihlášky VS",
    572: "Usnesení o nepřipuštění změny v osobě věřitele",
    573: "Usnesení o vrácení zálohy na insolvenční řízení",
    574: "Usnesení o vydání/vyplacení zálohy na náklady řízení správce",
    576: "Vrácení přihlášky",
    577: "Vrácení přihlášky soudu I.stupně",
    578: "Výzva likvidátorovi",
    579: "Zapůjčení přihlášky",
    580: "Záznam o vydání",
    581: "Zpětvzetí přihlášené pohledávky",
    582: "Žádost insolvenčního správce",
    583: "Žádost o prodloužení lhůty",
    584: "Usnesení o vzetí na vědomí částečného zpětvzetí přihlášky",
    585: "Předvolání k jednání",
    586: "Usnesení o zamítnutí žaloby",
    587: "Vykonatelnost",
    588: "Zpětvzetí",
    589: "VS - Rozsudek doplňující",
    590: "VS - Usnesení doplňující",
    591: "Rozhodnutí z incidenčního sporu",
    592: "Usnesení o část. nepřihlížení a odmítnutí přihlášky",
    593: "Usnesení o část. odmítnutí přihlášky",
    594: "Usnesení o část. ukončení účasti věřitele v insol. řízení",
    595: "Usnesení o nepřihlížení a odmítnutí přihlášky",
    596: "Usnesení o část.změně v osobě věřitele",
    597: "Směnka",
    598: "Návrh na určení lhůty",
    599: "Zpráva o mimořádných splátkách dle § 412 odst. 1 písm. b)",
    600: "Úřad práce - uspokojení mzdových nároků",
    601: "Výzva na doplnění dovolání",
    602: "Usnesení o odmítnutí jednoho z insolvenčních návrhů",
    603: "Usnesení o zamítnutí jednoho z insolvenčních návrhů",
    604: "Usnesení o zastavení řízení o návrhu na moratorium",
    605: "Usnesení o změně splátkového kalendáře",
    606: "Sdělení insolvenčního správce",
    607: "Vyřízení reklamace",
    608: "Konečná zpráva  - doplnění",
    609: "Dotaz na CEO",
    610: "Usnesení o ustanovení odděleného správce",
    611: "Usnesení o zproštění odděleného správce",
    612: "Zpětvzetí popření pohledávky dlužníkem",
    613: "Usnesení o ustanovení opatrovníka pro insolvenční řízení",
    614: "Usnesení o ustanovení opatrovníka pro doručování",
    615: "Pokyn účtárně k vymáhání",
    616: "Návrh na ustanovení předběžného správce",
    617: "Zaslání rozhodnutí s doložkou právní moci",
    618: "Záznam o složení",
    619: "Usnesení o zrušení oddlužení z důvodu úmrtí dlužníka",
    621: "Usnesení o spojení věci k společnému projednávání",
    623: "Oddělení spojené věci po PM",
    622: "Oddělení spojené věci",
    624: "Rozhodnutí soudu o určení procesní lhůty",
    625: "Zasílání údajů o změně osoby věřitele v přihlášce",
    627: "Převzetí vyžádaného spisu",
    628: "Zaslání rozhodnutí dovolacího soudu",
    629: "Rozhodnutí o odvolání - zrušeno a zastaveno",
    630: "Usnesení o schválení zprávy o reorganizačním plánu",
    631: "Záznam o složení jistoty",
    632: "Usnesení o neschválení zprávy o reorganizačním plánu",
    633: "Popření pohledávky přihlášeným věřitelem",
    634: "Usnesení o vyloučení věci k samostatnému řízení",
    635: "Usnesení o dodatečném zjištění popřené pohledávky",
    636: "Znepřístupnění údajů o dlužníkovi dle § 425 IZ",
    637: "Souhlas soudu se žádostí o vyškrtnutí dlužníka ze seznamu dlužníků",
    638: "Žaloba pro zmatečnost",
    639: "Rozhodnutí o žalobě pro zmatečnost - zrušení rozhodnutí",
    640: "Rozhodnutí o žalobě pro zmatečnost - zamítnutí žaloby",
    643: "Nový nápad",
    644: "Nový nápad po vyloučení",
    646: "Částečné zpětvzetí",
    647: "Doplnění žaloby/návrhu",
    648: "PO-usnesení o nařízení předběžného opatření",
    650: "PO-usnesení o nařízení se zrušuje",
    651: "PO-usnesení o odmítnutí",
    652: "PO-usnesení o zamítnutí",
    653: "PO-usnesení o zastavení",
    655: "Povinnost zaplatit Sop dle rozhodnutí",
    656: "Oznámení o procesním nástupnictví",
    657: "Prodloužená lhůta k napsání rozhodnutí",
    658: "Doplňková informace žalobce/navrhovatele",
    659: "Prodloužení lhůty k předložení spisu",
    660: "Protokol o provedení důkazů mimo jednání",
    661: "Protokol o veřejném vyhlášení rozsudku",
    662: "Protokol sepsaný mimo jednání",
    664: "Předkládací zpráva",
    665: "Předložení originálu směnky",
    666: "Předložení spisu dle § 104a o.s.ř.",
    667: "Doplňková informace žalovaného/odpůrce",
    668: "Předvolání ke smírčímu řízení",
    669: "Předvolání osoby s uloženou povinností při dokazování",
    670: "Předvolání osoby/statut.orgán práv.osoby",
    671: "Předvolání stát.zastupitelství k jednání nebo provedení důkazu",
    672: "Předvolání svědka",
    673: "Předvolání tlumočníka",
    674: "Předvolání účastníka k přípravnému jednání",
    675: "Předvolání účastníka k 1. jednání",
    676: "Předvolání účastníka k dalšímu jednání",
    677: "Předvolání účastníka k výslechu mimo jednání",
    678: "Doplňující rozsudek",
    679: "Předvolání zástupce účastníka k 1. jednání",
    680: "Předvolání zástupce účastníka k dalšímu jednání",
    681: "Předvolání zástupce účastníka k přípravě jednání",
    682: "Předvolání zástupce žalovaného k 1. jednání",
    683: "Předvolání znalce",
    684: "Předvolání žalovaného k 1. jednání",
    685: "Převedení jinému soudu",
    686: "Přílohový spis",
    687: "Přílohy",
    688: "Přílohy spisu",
    689: "Doplňující usnesení",
    690: "Přípis",
    691: "Přípis žalobci/zástupci žalobce",
    692: "Přípis žalovanému/zástupci žalovaného",
    694: "Půjčení spisu - bez S.O.",
    695: "Referát",
    696: "Referát pro v.s.ú.",
    697: "Rejstřík trestů",
    700: "Doručení podle Haagské úmluvy",
    701: "Rozhodnutí předsedy soudu",
    702: "Rozsudek pro uznání",
    703: "Rozsudek pro zmeškání",
    704: "Rozšíření žaloby",
    705: "Sdělení",
    706: "Sdělení o pohledávce",
    707: "Sdělení pro vyvěšení na ÚD+EÚD",
    708: "Sdělení vymáhajícího úředníka",
    709: "Skončená věc",
    710: "Doručení soudním doručovatelem",
    711: "Fotokopie směnky",
    712: "Splátkový kalendář - výzva na Sop",
    714: "Upřesnění žalobce/navrhovatele",
    716: "Urgence",
    717: "Úřední záznam",
    718: "Úschova soudu",
    719: "Usn. o částečném osvobození od SOP",
    720: "Doslání podání na VS",
    721: "Usn. o osvob. od SOP v plném rozsahu a ustan.zástupce",
    722: "Usn. o osvobození od SOP v plném rozsahu",
    723: "Usn. o povinnosti zaplatit SOP",
    724: "Usn. o vrácení SOP/přeplatku SOP",
    725: "Usn. o výzvě k zaplacení SOP/doplatku SOP",
    726: "Usnesení o výzvě k doplnění tvrzení",
    727: "Usnesení - jiné",
    728: "Usnesení - o nepřipuštění dalšího účastníka",
    729: "Usnesení - o nepřipuštění vedlejšího účastníka",
    730: "Usnesení - o nepřipuštění vstupu nového účastníka",
    731: "Dotaz",
    732: "Usnesení - o nepřipuštění zastoupení",
    733: "Usnesení - o nepřipuštění změny návrhu",
    734: "Usnesení - o nevyhovění",
    735: "Usnesení - o povinnosti zaplatit NŘ",
    736: "Usnesení - o prominutí pořádkové pokuty",
    737: "Usnesení - o prominutí zmeškání lhůty",
    738: "Usnesení - o připuštění částečné změny návrhu",
    739: "Usnesení - o připuštění dalšího účastníka do řízení",
    740: "Usnesení - o připuštění vedlejšího účastníka do řízení",
    741: "Usnesení - o připuštění změny návrhu",
    742: "Dovolání - jiné",
    743: "Usnesení - o vyhovění",
    744: "Usnesení - o zamítnutí žádosti o osvobození od Sop",
    746: "Usnesení - o zamítnutí žádosti o prominutí zmeškání lhůty",
    747: "Usnesení - o změně rozhodnutí",
    748: "Usnesení - o odmítnutí podání",
    749: "Usnesení - o prodloužení lhůty",
    750: "Usnesení - výzva k předložení listin",
    751: "Usnesení - výzva k vyjádření",
    752: "Usnesení - výzva vyjádřit se k odvolání/dovolání",
    753: "Částečný rozsudek",
    754: "Elektronické podání",
    755: "Usnesení - výzva, aby se účastník vyjádřil k žalobě",
    756: "Usnesení - zamítnutí návrhu",
    757: "Usnesení - zamítnutí návrhu na zrušení předběžného opatření",
    758: "Usnesení - zastavení řízení",
    759: "Usnesení - zpětvzetí neúčinné",
    760: "Usnesení - zrušení rozhodnutí",
    761: "Usnesení dle § 114b o.s.ř.",
    762: "Usnesení o částečném odmítnutí žaloby",
    763: "Usnesení o částečném zastavení řízení",
    764: "Usnesení o částečném zpětvzetí",
    765: "Evidenční karta diktafonového záznamu",
    766: "Usnesení o částečném zrušení rozsudku",
    767: "Usnesení o částečném zrušení usnesení",
    768: "Usnesení o neustanovení zástupce",
    769: "Usnesení o nákladech řízení",
    770: "Usnesení o odkladu vykonatelnosti",
    771: "Usnesení o odměně zástupci (ex offo)",
    772: "Usnesení o odmítnutí odvolání",
    773: "Usnesení o pokračování v přerušeném řízení",
    774: "Faxové podání",
    775: "Usnesení o procesním nástupnictví § 107a o.s.ř.",
    776: "Usnesení o procesním nástupnictví § 107 o.s.ř.",
    777: "Usnesení o přerušení řízení",
    778: "Usnesení o přerušení řízení po vydání rozhodnutí",
    779: "Usnesení o přiznání odměny opatrovníkovi",
    780: "Usnesení o přiznání tlumočného",
    781: "Usnesení o přiznání znalečného",
    782: "Usnesení o schválení smíru",
    783: "Usnesení o smíru - dílčí",
    784: "Usnesení o spojení věcí ke společnému projednání",
    785: "Informativní výslech",
    786: "Usnesení o určení svědečného",
    787: "Usnesení o uložení pokuty",
    788: "Usnesení o uložení povinnosti",
    789: "Usnesení o ustanovení advokáta opatrovníkem",
    790: "Usnesení o ustanovení opatrovníka",
    791: "Usnesení o přibrání tlumočníka",
    792: "Usnesení o ustanovení zástupce",
    793: "Usnesení o ustanovení znalce",
    794: "Usnesení o vrácení jistoty",
    795: "Usnesení o vyloučení věci k samostatnému projednání",
    796: "Jistota",
    797: "Usnesení o výzvě - zvolení advokáta pro dovolání",
    799: "Usnesení o zamítnutí návrhu",
    800: "Usnesení o zamítnutí přerušení řízení",
    801: "Usnesení o zastavení řízení - dílčí",
    802: "Usnesení o zastavení řízení o odvolání",
    803: "Usnesení o změně a zastavení",
    805: "Usnesení o zproštění funkce opatrovníka",
    807: "Usnesení o zproštění funkce tlumočníka",
    808: "Usnesení o zproštění funkce znalce",
    809: "Usnesení o zproštění zastupování",
    810: "Usnesení o zproštění znalce a jmenování nového",
    811: "Usnesení o zrušení rozsudku a zastavení řízení",
    812: "Usnesení o zrušení usn. pro nezaplacení Sop",
    813: "Usnesení o zrušení usnesení a zastavení řízení",
    814: "Usnesení o zrušení usnesení soudu I.stupně",
    815: "Usnesení s výzvou k odstranění vad odvolání",
    816: "Usnesení ÚS - jiné",
    817: "Konkurs prohlášen na žalobce/navrhovatele",
    818: "OP - Rozhodnutí ÚS o odmítnutí stížnosti",
    819: "OP - Ústavní stížnost",
    820: "Vrácení podání k opravě",
    821: "Vrácení příloh",
    824: "Vrácení spisu - z S.O.",
    825: "Vrácení spisu z jiného soudu k doplnění - v S.O.",
    826: "Vstup státního zástupce",
    827: "Vyjádření",
    828: "Konkurs prohlášen na žalovaného/odpůrce",
    829: "Výpis z katastru nemovitostí",
    831: "Výpis z živnostenského rejstříku",
    832: "Výpis/opis z rejstříku trestů",
    833: "Vyrozumění o odročení nebo odvolání jednání",
    834: "Vyrozumění o odročení nebo odvolání provedení důkazu",
    835: "Vyrozumění o odročení nebo odvolání přípravy jednání",
    836: "Vyrozumění účastníků a zástupců o provedení důkazu",
    837: "Výzva",
    838: "Mezitímní rozsudek",
    839: "Výzva k odstranění vad podání",
    840: "Výzva k vyzvednutí směnky",
    841: "Výzva pro vyvěšení na ÚD+EÚD",
    843: "Zaplacení Sop převodem",
    844: "Zaplacení Sop převodem u jiného soudu",
    845: "Zaplacení Sop v kolcích",
    846: "Zaslání dovolání",
    847: "Zaslání odvolání",
    848: "OP - Dovolání",
    849: "Zaslání žaloby žalovanému",
    850: "Záznam",
    852: "Záznam o složení",
    853: "Záznam z účtárny o vrácení",
    854: "Zpětvzetí",
    855: "Zpětvzetí jiné",
    856: "Zpětvzetí návrhu po vydání rozhodnutí",
    857: "Zpětvzetí odvolání",
    858: "Doložka právní moci",
    859: "OP - Návrh na povolení obnovy řízení",
    860: "Žádost",
    861: "Žádost na RT",
    862: "Žádost na katastrální úřad",
    863: "Žádost na OR",
    865: "Žádost o vyznačení doložky PM",
    866: "Žádost o doručení",
    867: "Žádost o odročení jednání",
    868: "Žádost o osvobození od zaplacení Sop",
    869: "Žádost o prodloužení lhůty",
    871: "Žádost o prominutí zmeškání lhůty",
    872: "Žádost o předvedení",
    873: "Žádost o stanovení odměny ustanoveného advokáta",
    874: "Žádost o zaslání spisu s odpovědí",
    875: "Žádost/návrh na ustanovení opatrovníka",
    876: "Žádost/návrh na vydání opravného usnesení",
    878: "Usnesení - výzva, zda účastník souhlasí s rozhodnutím bez jednání",
    879: "Urgence vrácení zapůjčeného spisu",
    880: "Výpis z CEO",
    882: "Vyúčtování náhrad z používání vozidla",
    883: "Žádost o nahlédnutí do spisu",
    884: "Žádost o zaslání spisu k nahlédnutí",
    885: "Žádost o sdělení čísla účtu",
    886: "Vrácení směnky",
    888: "VS - Rozsudek - potvrzeno",
    889: "VS - Rozsudek - změna",
    891: "VS - Rozsudek -zrušeno a vráceno",
    892: "VS - Usnesení - potvrzeno",
    893: "VS - Usnesení - změna",
    894: "VS - Usnesení - zrušeno a vráceno",
    895: "VS - Usnesení - jinak",
    896: "VS - Usnesení - odvolací řízení zastaveno",
    897: "VS - Usnesení - odvolání odmítnuto",
    897: "VS - Usnesení - odvolání odmítnuto",
    898: "VS - Vrácení bez věcného vyřízení",
    899: "OP - Usnesení o zamítnutí obnovy",
    900: "VS - Převzetí odvolání nadřízeným soudem",
    901: "VS - Opětovné převzetí odvolání nadřízeným soudem",
    902: "VS - Vrácení spisu soudu I. stupně",
    903: "VS - Protokol o hlasování",
    904: "VS - Usnesení o delegaci",
    906: "VS - Usnesení o příslušnosti",
    907: "VS - Usnesení o tom, zda je soudce vyloučen",
    908: "NS – Rozhodnutí o delegaci",
    909: "NS – Rozhodnutí o podjatosti",
    910: "OP - Usnesení o zamítnutí žaloby pro zmatečnost",
    911: "NS – Rozhodnutí o příslušnosti",
    912: "NS – Převzetí věci Nejvyšším soudem",
    913: "NS – Protokol o hlasování",
    914: "NS – Zaslání rozhodnutí dovolacího soudu a vrácení spisu",
    915: "NS – Zaslání rozhodnutí dovolacího soudu bez spisu",
    916: "NS – Rozhodnutí NS o dovolání – jinak",
    917: "NS – Rozhodnutí NS o dovolání – odmítnutí",
    918: "NS – Rozhodnutí NS o dovolání – zamítnutí",
    919: "NS – Rozhodnutí NS o dovolání – zastavení řízení",
    920: "NS – Rozhodnutí NS o dovolání – zrušení a vrácení odvolacímu soudu",
    921: "OP - Usnesení o vyhovění žalobě - zrušení rozhodnutí I.stupně",
    922: "NS – Rozhodnutí NS o dovolání – zrušení a vrácení soudu I. stupně",
    923: "NS – Rozhodnutí NS o dovolání – zrušení a zastavení řízení",
    924: "Oddělení spojené věci po právní moci",
    927: "Vyjádření k žalobě",
    929: "Pověření asistenta soudce/VSÚ",
    930: "Opatření o příkázání věci jinému soudci",
    932: "OP - Žaloba pro zmatečnost",
    936: "Usnesení o zamítnutí námitky podjatosti",
    938: "Návrh dle § 107a o.s.ř.",
    939: "Návrh na delegaci z důvodu vhodnosti",
    940: "Návrh na pokračování v řízení",
    941: "Návrh na přerušení řízení",
    942: "Návrh na přistoupení dalšího účastníka do řízení",
    943: "Návrh na spojení věcí",
    944: "Doplnění částečného zpětvzetí",
    945: "Návrh na určení lhůty (§ 174a zák.č.6/2002 Sb.)",
    946: "Návrh na určení příslušnosti soudu",
    947: "Návrh na vydání předběžného opatření",
    948: "Návrh na zajištění důkazů",
    950: "Návrh na zrušení rozsudku pro zmeškání",
    952: "Odeslání spisu - v S.O.",
    953: "Odpověď na dotaz",
    954: "Odpověď na reklamaci doručenky",
    955: "Doplnění odvolání",
    956: "Odpověď na výzvu",
    957: "Odpověď na žádost",
    958: "Odročeno na neurčito",
    959: "Odročeno s rezervací",
    960: "Odůvodnění dovolání",
    961: "Odvolání jednání s rezervací",
    962: "Odvolání jiné",
    963: "Odvolání plné moci",
    964: "Odvolání vzato zpět",
    965: "Doplnění podání žalobce/navrhovatele",
    966: "Omluva na jednání",
    967: "OP - podání odvolání do PO",
    968: "OP - odvolání do rozhodnutí",
    969: "Opětovné doručení",
    970: "Opravné usnesení vedlejší",
    971: "Opravné usnesení",
    972: "Oznámení katastrálnímu úřadu",
    973: "Oznámení o ukončení zastupování",
    974: "Oznámení pro vyvěšení na ÚD+EÚD",
    975: "Platba jiná",
    976: "Doplnění podání žalovaného/odpůrce",
    977: "Platební poukaz",
    978: "Platební poukaz - likvidátor,ustan.advokát",
    979: "Platební poukaz - svědečné",
    980: "Platební poukaz - tlumočné",
    981: "Platební poukaz - znalečné",
    982: "Plná moc",
    983: "Pokračování v přerušeném řízení",
    984: "Pokus o smír",
    985: "Potvrzení o osobních a majetkových poměrech-k předání účastníkovi",
    986: "Potvrzení o přijetí",
    987: "Doplnění zpětvzetí",
    988: "Poučení o námitce podjatosti",
    989: "Poučení o procesních právech a povinnostech účastníka",
    990: "Poučení účastníka o právu vyjádřit se k osobám soudců",
    992: "Poukaz účtárně k vrácení Sop",
    993: "Poukaz účtárně na vrácení jistoty",
    994: "Poukaz účtárně na vrácení zálohy",
    995: "Poukaz účtárně na vrácení pokuty",
    997: "PO-usnesení o část.nařízení a část.zamítnutí",
    998: "Vyrozumění o popření přihlášené pohledávky",
    999: "Usnesení o zastavení dovolacího řízení",
    1000: "Usnesení o zastavení odvolacího řízení",
    1001: "Návrh na prohlášení konkursu",
    1002: "Usnesení o zastavení řízení vůči zemřelému dlužníkovi",
    1003: "Výpis z CEO",
    1004: "Usnesení o zamítnutí návrhu na změnu věřitele",
    1005: "Usnesení o odmítnutí odvolání pro opožděnost",
    1006: "Usnesení o vrácení SOP/přeplatku SOP",
    1007: "Seznam majetku a závazků",
    1008: "Vyúčtování nákladů",
    1009: "Zpětvzetí popření pohledávky věřitelem",
    1010: "NS - Rozhodnutí NS - výzva",
    1011: "NS - Přípis",
    1012: "NS - Rozhodnutí NS - opravné",
    1013: "NS - Rozhodnutí NS - procesní nástupnictví",
    1014: "NS - Rozhodnutí NS - odložení vykonatelnosti",
    1015: "NS - Rozhodnutí NS - odložení právní moci",
    1016: "NS - Rozhodnutí NS o dovolání - měnící",
    1017: "NS - Protokol o vyhlášení rozsudku",
    1018: "Vyhláška o zahájení insolvenčního řízení dalšího dlužníka",
    1019: "Sdělení o vzájemné souvislosti spisů",
    1020: "Zrušení vzájemné souvislosti spisů",
    1023: "Výpis údajů ze základních registrů",
    1024: "Výzva zahraničním věřitelům dle § 430 IZ",
    1025: "Pohledávka za majetkovou podstatou",
    1026: "Sdělení účtárny",
    1027: "Smlouva",
    1028: "Smlouva o prodeji mimo dražbu",
    1029: "Usnesení o odmítnutí dovolání",
    1030: "Doplnění žádosti",
    1031: "Výzva k podání žaloby na určení pořadí uplatněné pohledávky ( § 203a IZ)",
    1032: "Pokyn zajištěného věřitele",
    1033: "Usnesení o pokynu zajištěného věřitele",
    1034: "Usnesení o zamítnutí návrhu na osvobození od placení pohledávek",
    1035: "Usnesení o nezveřejnění insolvenčního návrhu",
    1036: "Zpráva pro oddlužení",
    1037: "Zpráva o přezkumu",
    1038: "Usnesení o zprávě o přezkumu",
    1039: "Záznam o jednání s dlužníkem",
    1040: "Usnesení o uložení pokuty podle insolvenčního zákona",
    1041: "Usnesení o odmítnutí/zastavení námitek",
    1042: "Usnesení o potvrzení/změně/vyhovění námitkám",
    1043: "Usnesení o odmítnutí popření pohledávky přihlášeným věřitelem",
    1044: "Žádost dlužníka",
    1045: "Žádost o vyškrtnutí dlužníka ze seznamu dlužníků",
    1046: "Zpráva IS o splnění oddlužení",
    1047: "Usnesení o zaplacení zálohy na náklady důkazu",
    1048: "Vzájemný návrh",
    1049: "Usnesení o neschválení oddlužení a zastavení řízení",
    1050: "Usnesení o zrušení schváleného oddlužení a zastavení řízení",
    1051: "Usnesení o odmítnutí návrhu na povolení oddlužení a zastavení řízení",
    1052: "Usnesení o zamítnutí návrhu na povolení oddlužení a zastavení řízení",
    1053: "Vyhláška o zprávě o přezkumu a zprávě pro oddlužení",
    1054: "Zpráva insolvenčního správce"
}

mapaSoudu = {
    'KSJIMBM': 'Krajský soud v Brně',
    'KSJICCB': 'Krajský soud v Českých Budějovicích',
    'KSVYCHK': 'Krajský soud v Hradci Králové',
    'KSVYCPA': 'Krajský soud v Hradci Králové pobočka Pardubice',
    'KSSEMOS': 'Krajský soud v Ostravě',
    'KSSEMOC': 'Krajský soud v Ostravě pobočka Olomouc',
    'KSZPCPM': 'Krajský soud v Plzni',
    'KSSTCAB': 'Krajský soud v Praze',
    'KSSCEUL': 'Krajský soud v Ústí nad Labem',
    'KSSCELB': 'Krajský soud v Ústí nad Labem pobočka Liberec'
}

druhStavRizeni = "KONKURS,VYRIZENA,OBZIVLA,ZRUŠENO VS,ODDLUŽENÍ,MORATORIUM,ODSKRTNUTA,PRAVOMOCNA,NEVYRIZENA,MYLNÝ ZÁP.,ÚPADEK".split(',')

# CCA = asi admini?
idOsobyPuvodce = "KSSTCAB,KSSCEUL,KSZPCPM,KSJIMBM,MSPHAAB,KSSEMOS,KSJICCB,KSVYCHK".split(',')
