#!/usr/bin/env python
#coding=utf-8

META = ["idOsobyPuvodce", "druhStavRizeni", "nazevOsoby", "idOsoby",
        "druhRoleVRizeni", "druhOsoby", "jmeno", "rc", "datumPobytOd",
        "adresa", "psc", "mesto", "idAdresy", "cisloPopisne", "ulice",
        "datumNarozeni", "ic", "druhPravniForma", "titulPred", "okres", "zeme",
        "druhSpravce", "nazevOsobyObchodni", "priznakAnInterniCisUdalost",
        "popisCisUdalosti", "datumZalozeniCisUdalosti", "cisUdalost",
        "telefon", "fax", "datumZruseniCisUdalosti", "priznakAnVedlejsiUdalost",
        "priznakAnVedlejsiDokument", "datumPravniMoci", "bcVecHlavni",
        "druhVecHlavni", "rocnikHlavni", "datumSpojeni", "priznakMylnyZapisVeritelPohled",
        "priznakPlatnyVeritel", "datumOddeleni", "datumZverejneniOpraveneUdalosti",
        "datumOsobaVeVeciZrusena", "titulZa", "dic", "datumUstanoveniSpravce"]

KODY = {
    "1": "Změna osoby",
    "2": "Změna adresy osoby",
    "4": "Změna v číselníku událostí",
    "5": "Insolvenční návrh",
    "6": "Insolvenční návrh spojený s návrhem na povolení oddlužení",
    "7": "Insolvenční návrh spojený s návrhem na povolení reorganizace",
    "8": "Návrh",
    "9": "Návrh na předběžné opatření",
    "10": "Návrh na moratorium",
    "11": "Návrh na zrušení moratoria",
    "12": "Návrh na vynětí majetku z majetkové podstaty",
    "13": "Návrh na povolení reorganizace",
    "16": "Návrh změny reorganizačního plánu",
    "17": "Návrh na přeměnu reorganizace v konkurs",
    "18": "Návrh na povolení oddlužení",
    "19": "Návrh na osvobození od placení dosud neuspokojených pohledávek",
    "20": "Návrh na zrušení schváleného oddlužení",
    "21": "Návrh - zpětvzetí",
    "22": "Návrh - doplnění návrhu",
    "23": "Návrh - přílohy",
    "24": "Námitky",
    "25": "Námitky proti konečné zprávě",
    "26": "Námitky proti povolení oddlužení dle § 403 odst. 2",
    "27": "Žaloba",
    "28": "Sdělení",
    "29": "Sdělení dlužníka",
    "30": "Sdělení věřitele",
    "31": "Sdělení známého věřitele o pohledávce",
    "32": "Sdělení finančního úřadu",
    "33": "Sdělení banky",
    "34": "Sdělení živnostenského úřadu",
    "35": "Sdělení Ministerstva vnitra (auta)",
    "36": "Sdělení Střediska cenných papírů",
    "37": "Sdělení Katastru nemovitostí",
    "38": "Sdělení dlužníka o nepředložení reorganizačního plánu",
    "39": "Sdělení správce o plnění oddlužení",
    "40": "Sdělení dlužníka o plnění oddlužení",
    "41": "Vyjádření",
    "42": "Vyjádření dlužníka",
    "43": "Vyjádření navrhovatele",
    "44": "Dotaz na stav řízení",
    "45": "Stížnost",
    "46": "Stížnost dlužníka",
    "47": "Stížnost věřitele",
    "48": "Zpráva",
    "49": "Zpráva o hospodářské situaci dlužníka",
    "50": "Zpráva o průběhu zpeněžení",
    "51": "Zpráva o plnění reorganizačního plánu",
    "52": "Zpráva dlužníka o svých příjmech dle § 412 odst. 1 písm. d)",
    "53": "Zpráva dlužníka o změně údajů dle § 412 odst. 1 písm. c)",
    "54": "Znalecký posudek",
    "55": "Plná moc",
    "56": "Výpis",
    "58": "Výpis z obchodního rejstříku",
    "59": "Reorganizační plán",
    "60": "Reorganizační plán - zpráva",
    "61": "Jiné podání",
    "62": "Hlasovací lístek",
    "63": "Přihláška pohledávky",
    "64": "Seznam přihlášených pohledávek",
    "65": "Seznam přihlášených pohledávek - výpis",
    "66": "Usnesení",
    "67": "Usnesení o vyhlášení moratoria",
    "68": "Usnesení o odmítnutí návrhu na moratorium",
    "69": "Usnesení o prodloužení moratoria",
    "70": "Usnesení o zrušení moratoria",
    "71": "Usnesení o nevyhovění návrhu na zrušení moratoria",
    "72": "Usnesení o odmítnutí insolvenčního návrhu",
    "73": "Usnesení o zastavení řízení pro zpětvzetí insolvenčního návrhu",
    "74": "Usnesení o neúčinnosti zpětvzetí insolvenčního návrhu",
    "75": "Usnesení o úpadku",
    "76": "Usnesení o úpadku spojené s prohlášením konkursu",
    "77": "Usnesení o úpadku spojené s povolením reorganizace",
    "78": "Usnesení o úpadku spojené s povolením oddlužení",
    "79": "Usnesení o způsobu řešení úpadku konkursem dle usnesení schůze věřitelů",
    "81": "Usnesení o zastavení řízení pro nedostatek podmínky řízení",
    "82": "Usnesení o zamítnutí insolvenčního návrhu",
    "83": "Usnesení o zamítnutí insolvenčního návrhu pro nedostatek majetku dlužníka",
    "84": "Usnesení o tom, že dlužník není v úpadku",
    "85": "Usnesení o vydání předběžného opatření",
    "86": "Usnesení o zrušení předběžného opatření",
    "87": "Usnesení o zastavení řízení pro nezaplacení zálohy na náklady řízení",
    "88": "Usnesení o ustanovení předběžného správce",
    "89": "Usnesení o záloze na náklady předběžného správce",
    "90": "Usnesení o hotových výdajích a odměně předběžného správce",
    "91": "Usnesení o ustanovení znalce",
    "92": "Usnesení o schválení odměny znalce",
    "94": "Usnesení o prohlášení konkursu",
    "95": "Usnesení o zrušení konkursu",
    "96": "Usnesení o schválení zprávy správce po úmrtí dlužníka",
    "97": "Usnesení o nepatrném konkursu",
    "98": "Usnesení o zrušení rozhodnutí o nepatrném konkursu",
    "99": "Usnesení o povolení reorganizace",
    "103": "Usnesení o zastavení řízení o žalobě",
    "104": "Usnesení o smíru",
    "105": "Usnesení o ustanovení správce",
    "106": "Usnesení o potvrzení správce zvoleného schůzí věřitelů",
    "108": "Usnesení o odvolání správce z funkce",
    "109": "Usnesení o zproštění funkce správce pro porušení povinností",
    "110": "Usnesení o zproštění funkce správce po skončení řízení",
    "113": "Usnesení o zrušení usnesení schůze věřitelů",
    "114": "Usnesení o zamítnutí návrhu na zrušení usnesení schůze věřitelů",
    "115": "Usnesení o potvrzení volby členů a náhradníků věřitelského orgánu",
    "116": "Usnesení o jmenování prozatímního věřitelského výboru",
    "117": "Usnesení o jmenování členů a náhradníků věřitelského výboru",
    "118": "Usnesení o odměně a náhradě nutných výdajů likvidátora",
    "119": "Usnesení o odvolání z funkce člena nebo náhradníka věřitelského výboru",
    "120": "Usnesení o změně věřitelského orgánu v souvislosti s postupem pohledávky",
    "121": "Usnesení o odvolání věřitelského výboru",
    "122": "Usnesení o uložení pořádkové pokuty",
    "123": "Usnesení o předvolání k výslechu",
    "124": "Usnesení o odmítnutí přihlášky",
    "125": "Usnesení o tom, že se k přihlášce nepřihlíží",
    "126": "Usnesení o vzetí na vědomí zpětvzetí přihlášky",
    "128": "Usnesení o ukončení účasti věřitele v insolvenčním řízení",
    "129": "Usnesení o opatřeních potřebných k zjištění majetkové podstaty a způsobu zjištění",
    "134": "Usnesení o vynětí majetku z majetkové podstaty",
    "135": "Usnesení o neúčinnosti právního úkonu",
    "138": "Usnesení o skončení provozu dlužníkova podniku",
    "139": "Usnesení o pokračování v přerušeném řízení",
    "141": "Usnesení o schválení dohody o vypořádání SJM",
    "144": "Usnesení o opatření k vynucení splnění uložených povinností",
    "145": "Usnesení o prodloužení lhůty ke splnění povinností",
    "146": "Usnesení o povolení výjimky ze zákazu nabývání majetku z majetkové podstaty",
    "147": "Usnesení o pořadí úhrady pohledávky",
    "148": "Usnesení o povolení částečného rozvrhu",
    "149": "Usnesení o konečné zprávě",
    "150": "Usnesení o zákazu nakládat s majetkovou podstatou",
    "151": "Usnesení o omezení nakládat s majetkovou podstatou",
    "152": "Usnesení o odmítnutí návrhu na povolení reorganizace pro opožděnost",
    "153": "Usnesení o odmítnutí návrhu na povolení reorganizace pro vady",
    "154": "Usnesení o vzetí na vědomí zpětvzetí návrhu na povolení reorganizace",
    "156": "Usnesení o zamítnutí návrhu na povolení reorganizace",
    "158": "Usnesení o schválení reorganizačního plánu",
    "159": "Usnesení o schválení změny reorganizačního plánu",
    "161": "Usnesení o zamítnutí reorganizačního plánu",
    "163": "Usnesení o přeměně reorganizace v konkurs",
    "164": "Usnesení o vzetí na vědomí splnění reorganizačního plánu",
    "165": "Usnesení o odměně správce",
    "166": "Usnesení o zastavení řízení dle § 427",
    "167": "Usnesení o odmítnutí návrhu na povolení oddlužení pro vady",
    "168": "Usnesení o odmítnutí návrhu na povolení oddlužení pro opožděnost nebo neoprávněnost",
    "169": "Usnesení o vzetí na vědomí zpětvzetí návrhu na povolení oddlužení",
    "171": "Usnesení o zamítnutí návrhu na povolení oddlužení",
    "172": "Usnesení o povolení oddlužení",
    "173": "Usnesení o způsobu oddlužení dle § 402 odst. 5",
    "174": "Usnesení o schválení oddlužení zpeněžením majetkové podstaty",
    "175": "Usnesení o schválení oddlužení plněním splátkového kalendáře",
    "176": "Usnesení o neschválení oddlužení",
    "177": "Usnesení o vzetí na vědomí splnění oddlužení",
    "178": "Usnesení o osvobození dlužníka od placení dosud neuspokojených pohledávek",
    "181": "Usnesení o zrušení schváleného oddlužení",
    "182": "Dotaz",
    "183": "Rozsudek",
    "184": "Vyhláška",
    "185": "Vyhláška o zahájení insolvenčního řízení",
    "186": "Vyhláška o svolání schůze věřitelů",
    "187": "Vyhláška o svolání přezkumného jednání",
    "188": "Vyhláška o konečné zprávě",
    "189": "Výzva",
    "190": "Usnesení o uložení povinnosti zaplatit zálohu",
    "191": "Výzva věřitelům k podávání přihlášek pohledávek",
    "192": "Výzva na doplnění příloh insolvenčního návrhu",
    "193": "Výzva na předložení seznamů k insolvenčnímu návrhu",
    "194": "Výzva dlužníkovi k vyjádření se k insolvenčnímu návrhu",
    "195": "Výzva na správce",
    "196": "Výzva na odstranění vad návrhu na vynětí majetku",
    "197": "Výzva k opravě nebo doplnění návrhu na povolení reorganizace",
    "198": "Výzva k předložení reorganizačního plánu",
    "199": "Výzva k opravě nebo doplnění návrhu na povolení oddlužení",
    "200": "Výzva na zprávu správce o plnění oddlužení",
    "201": "Výzva na zprávu dlužníka o plnění oddlužení",
    "202": "Výzva k opravě nebo doplnění návrhu",
    "203": "Výzva na podání žaloby dle § 100 odst. 2",
    "204": "Pokyn insolvenčního soudu",
    "205": "Souhlas",
    "210": "Vyrozumění",
    "212": "Protokol",
    "213": "Protokol o prohlášení o postoupení pohledávky",
    "214": "Protokol ze schůze věřitelů",
    "215": "Protokol o jednání",
    "217": "Protokol o prohlášení o majetku",
    "218": "Rozvrhové usnesení",
    "219": "Předkládací zpráva",
    "220": "Svolání",
    "222": "Nařízení jednání",
    "223": "Úřední záznam",
    "224": "Záznam o nahlédnutí do spisu",
    "226": "Konečná zpráva",
    "227": "Opatření",
    "228": "Opatření o určení osoby správce",
    "230": "Odvolání",
    "231": "Odvolání - doplnění",
    "232": "Odvolání - zpětvzetí odvolání",
    "233": "Vrácení spisu",
    "234": "Zapůjčení spisu",
    "236": "Záznam o nahlížení do spisu",
    "237": "Vrácení spisu soudu I. stupně",
    "238": "Mylný zápis",
    "239": "Jiné",
    "241": "Výzva",
    "242": "Výzva na doplnění odvolání",
    "243": "Výzva k vyjádření se k odvolání",
    "245": "Usnesení na doplnění odvolání",
    "246": "Usnesení k vyjádření se k odvolání",
    "247": "Usnesení o změně v osobě věřitele",
    "311": "Rozhodnutí o odvolání ve věci zproštění funkce insolv. správce, jeho výdajích a způsob úhrady - jiné",
    "328": "Rozhodnutí opravné usnesení",
    "329": "Záznam o mylném zařazení",
    "330": "Změna XSD dokumentu poznámky",
    "331": "Náhradní doručení",
    "332": "Zpráva IS o stavu řízení",
    "333": "Dohoda o vypořádání SJM",
    "334": "Soupis majetkové podstaty",
    "335": "Dražební vyhláška",
    "336": "Protokol o vydražení",
    "337": "List vlastnictví",
    "338": "Návrh rozvrhového usnesení",
    "339": "Návrh na schválení dohody o vypořádání SJM",
    "340": "Návrh na svolání schůze věřitelů",
    "341": "Návrh částečného rozvrhového usnesení",
    "342": "Návrh na vydání opravného usnesení",
    "343": "Návrh na změnu v osobě věřitele",
    "344": "Návrh na zrušení konkurzu",
    "345": "Návrh na zrušení předběžného opatření",
    "346": "Návrh na vydání výtěžku zpeněžení zajištěnému věřiteli",
    "347": "Návrh na vydání souhlasu se zpeněžením MP mimo dražbu",
    "348": "Omluva",
    "349": "Zpráva IS o splnění rozvrhového usnesení",
    "350": "Zpráva IS po zrušení konkursu",
    "351": "Platební poukaz",
    "353": "Záznam o složení peněz do soudní úschovy",
    "354": "Pověření asistenta soudce",
    "355": "Pověření vyššího soudního úředníka",
    "356": "Prezenční listina",
    "357": "Přípis",
    "358": "Sdělení o vstupu KSZ do řízení",
    "359": "Vstup státního zastupitelství do řízení",
    "360": "Výstupu státního zastupitelství z řízení",
    "362": "Usnesení o ustanovení tlumočníka",
    "363": "Vyúčtování odměny znalce nebo tlumočníka",
    "365": "Výzva k zaplacení SOP",
    "366": "Zaplacení SOP",
    "367": "Žádost",
    "368": "Náhradní doručení",
    "369": "Právní moc",
    "370": "Právní moc konečného rozhodnutí",
    "371": "Informační zpráva",
    "372": "Změna stavu věci",
    "373": "Rozhodnutí o odvolání - potvrzeno",
    "374": "Rozhodnutí o odvolání - změněno",
    "375": "Rozhodnutí o odvolání - zrušeno a vráceno",
    "376": "Rozhodnutí o odvolání - zastavení řízení",
    "377": "Rozhodnutí o odvolání - odmítnuto",
    "378": "Rozhodnutí o odvolání - jinak",
    "380": "Zaslání rozhodnutí odvolacího soudu",
    "381": "Zaslání rozhodnutí odvolacího soudu a vrácení spisu",
    "382": "Převzetí věci Vrchním soudem",
    "383": "Rozhodnutí o tom, zda je soudce vyloučen",
    "384": "Rozhodnutí o delegaci",
    "386": "Protokol o hlasování",
    "387": "Žádost o zapůjčení spisu",
    "388": "Příprava jednání",
    "389": "Protokol o vyhlášení rozhodnutí",
    "390": "Předložení věci Nejvyššímu soudu",
    "391": "Rozhodnutí VS/NS o určení příslušnosti",
    "392": "Předložení věci vrchnímu soudu",
    "393": "Přípis - bez věcného vyřízení",
    "399": "Rozhodnutí o dovolání - zrušeno a vráceno soudu 1. stupně",
    "402": "Zaslání rozhodnutí dovolacího soudu a vrácení spisu",
    "403": "Rozhodnutí o místní příslušnosti (§ 11 odst. 3 OSŘ)",
    "404": "Převzetí věci Nejvyšším soudem",
    "405": "Změna senátu věci",
    "406": "Doručení do ciziny",
    "407": "Dovolání",
    "408": "Dovolání - doplnění dovolání",
    "409": "Dovolání - zpětvzetí dovolání",
    "410": "Insolvenční návrh spojený s návrhem na prohlášení konkursu",
    "411": "Námitka podjatosti",
    "412": "Námitky dle § 373 IZ",
    "413": "Přihláška - návrh na vstup nového věřitele",
    "414": "Návrh dlužníka",
    "415": "Návrh na odvolání správce",
    "416": "Návrh na odvolání z funkce ve v.v.",
    "417": "Návrh na pokračování v řízení",
    "418": "Návrh na rozhodnutí o hlasovacím právu",
    "419": "Návrh na úpravu seznamu přihlášených pohledávek",
    "420": "Návrh na uspokojení pohledávky za podstatou",
    "421": "Návrh na uspokojení zajištěného věřitele",
    "423": "Návrh na zproštění správce z funkce",
    "424": "Návrh veřitelského výboru",
    "425": "Odvolání jiné",
    "426": "Omluva",
    "427": "Oznámení",
    "428": "Oznámení soudu",
    "429": "Oznámení o změně konání jednání",
    "430": "Platební poukaz",
    "431": "Pokračování v řízení po zpětvzetí",
    "432": "Protokol z jednání věřitelského výboru",
    "434": "Předvolání k výslechu",
    "435": "Předvedení k soudu",
    "436": "Převedení spisu příslušnému soudu",
    "437": "Předvolání ke slyšení",
    "438": "Převzetí spisu z jiného soudu",
    "439": "Přezkumné jednání",
    "440": "Přihláška pohledávky - částečné zpětvzetí",
    "441": "Přihláška pohledávky - doplnění, oprava",
    "442": "Přihláška pohledávky - zpětvzetí",
    "443": "Příloha k protokolu o jednání",
    "444": "Přistoupení k řízení (§ 107 IZ)",
    "445": "Referát",
    "446": "Referát pro judikaturu",
    "447": "Sdělení o odstoupení z funkce ve v.v.",
    "448": "Sdělení o osobě jednající jménem člena/náhradníka v.o.",
    "449": "Seznam přihlášených pohledávek - změna",
    "450": "Seznam/upravený seznam přihlášených pohledávek",
    "451": "Schůze věřitelů",
    "452": "Souhlas s určením zastupující osoby",
    "453": "Soupis majetkové podstaty",
    "454": "Soupis majetkové podstaty - doplnění",
    "455": "Usnesení o nepotvrzení volby v.v.",
    "456": "Usnesení o uspokojení pohledávky za podstatou",
    "457": "Usnesení o doplnění/změně konečné zprávy",
    "458": "Usnesení o nařízení předběžného opatření bez návrhu",
    "460": "Usnesení o neschválení dohody o vypořádání SJM",
    "461": "Usnesení o odměně a hotových výdajích tlumočníka",
    "462": "Usnesení o odmítnutí konečné zprávy",
    "463": "Usnesení o odmítnutí návrhu na předběžné opatření",
    "464": "Usnesení o postoupení věci",
    "465": "Usnesení o prominutí pořádkové pokuty",
    "466": "Usnesení o schválení konečné zprávy",
    "467": "Usnesení o ukončení lhůty k předložení reorganizačního plánu",
    "468": "Usnesení o uložení povinnosti",
    "469": "Usnesení o vyloučení z rozvrhu",
    "470": "Usnesení o vyplacení zálohy na odměnu správce",
    "471": "Usnesení o zamítnutí návrhu na předběžné opatření",
    "472": "Usnesení o zániku pohledávky",
    "473": "Usnesení o zastavení řízení",
    "474": "Usnesení o zastavení řízení o předběžném opatření",
    "475": "Usnesení o zastavení řízení vůči učastníku (§ 130 odst. 2 IZ)",
    "476": "Usnesení o změně v osobě znalce",
    "477": "Usnesení o změně rozhodnutí soudu I.stupně",
    "478": "Usnesení o zrušení rozhodnutí soudu I.stupně",
    "479": "Usnesení o uplynutí lhůty",
    "480": "Vrácená obálka",
    "481": "Vrácení příloh",
    "482": "Vyhláška o hlasování",
    "483": "Vyhláška o jednání o konečné zprávě",
    "484": "Vyhláška o svolání zvláštního přezkumného jednání",
    "485": "Výpis z evidence ARES",
    "486": "Vyrozumění o soupisu majetkové podstaty",
    "487": "Vyřízeno jiným způsobem",
    "488": "Vyúčtování odměny a výdajů správce",
    "489": "Výzva k odstranění odlišnosti návrhů",
    "490": "Vzdání se práva odvolání",
    "491": "Zahraniční insolvenční správce",
    "492": "Zápis v rejstříku ukončen",
    "493": "Zaslání doplnění přihlášky správci",
    "494": "Zaslání přihlášky/přihlášek správci",
    "495": "Záznam o složení zálohy",
    "496": "Záznam o zaplacení zálohy na insolvenční řízení",
    "497": "Zkrácené znění usnesení",
    "498": "Zpětvzetí popření pohledávky insolvenčním správcem",
    "499": "Zvláštní přezkumné jednání",
    "501": "Žádost o určení osoby správce",
    "502": "Rozhodnutí o odvolání - potvrzeno",
    "503": "Rozhodnutí o odvolání - změněno",
    "504": "Rozhodnutí o odvolání - zrušeno a vráceno",
    "506": "Rozhodnutí o odvolání - odmítnuto",
    "507": "Rozhodnutí o odvolání - jinak",
    "508": "Zaslání rozhodnutí odvolacího soudu",
    "510": "Převzetí věci vrchním soudem",
    "511": "Rozhodnutí NS o dovolání - zastavení řízení",
    "512": "Rozhodnutí NS o dovolání - odmítnutí",
    "513": "Rozhodnutí NS o dovolání - zamítnutí",
    "514": "Rozhodnutí NS o dovolání - zrušení a vrácení odvolacímu soudu",
    "515": "Rozhodnutí NS o dovolání - zrušení a vrácení soudu 1. stupně",
    "517": "Rozhodnutí NS o dovolání - jinak",
    "524": "Protokol o hlasování",
    "525": "Žádost o zapůjčení spisu",
    "528": "Rozhodnutí o místní příslušnosti",
    "529": "Zpětvzetí návrhu",
    "530": "Návrh reorganizačního plánu",
    "531": "Protokol o prohlídce prostor",
    "532": "Opravné usnesení",
    "533": "Sdělení Ministerstva vnitra (auta)",
    "534": "Výpis ze seznamu přihlášených pohledávek",
    "535": "Usnesení o prodeji mimo dražbu",
    "536": "Usnesení o zpěněžení podniku",
    "537": "Usnesení o uspokojení zajištěného věřitele",
    "538": "Soupis majetkové podstaty - změna",
    "539": "Usnesení o svolání věřitelského výboru",
    "540": "Usnesení o nařízení prohlídky prostor",
    "541": "Rozhodnutí jiného soudu",
    "542": "Usnesení o odmítnutí žaloby",
    "544": "Výzva k podávání přihlášek pohledávek",
    "545": "Vyhláška o výzvě k podávání přihlášek pohledávek",
    "546": "Návrh na moratorium k insolvenčnímu návrhu",
    "547": "Usnesení o vyhlášení moratoria - po insolvenčním návrhu",
    "548": "Zánik moratoria",
    "549": "Zánik moratoria - po insolvenčním návrhu",
    "550": "Usnesení o zrušení moratoria - po insolvenčním návrhu",
    "551": "Návrh na prodloužení moratoria",
    "552": "Usnesení o změně rozhodnutí soudu I.stupně (bez změny stavu)",
    "553": "Usnesení o zrušení rozhodnutí soudu I.stupně (bez změny stavu)",
    "554": "Opětovné doručení vyhláškou",
    "555": "Usnesení o změně insolvenčního správce",
    "556": "Reklamace doručenky",
    "557": "Usnesení o prodloužení moratoria",
    "558": "Usnesení o prodloužení moratoria - po insolvenčním návrhu",
    "559": "Usnesení o odmítnutí návrhu na moratorium - po insolvenčním návrhu",
    "560": "Rozhodnutí o důvodnosti postoupení",
    "561": "Konečný/Závěrečný referát",
    "562": "Částečné zpětvzetí přihlášené pohledávky",
    "563": "Doplnění/oprava/změna přihlášené pohledávky",
    "564": "Odpověď na reklamaci doručenky",
    "565": "Odročení jednání",
    "566": "Odvolání do předběžného opatření",
    "567": "Odvolání jednání",
    "568": "Protokol z přezkumného jednání",
    "569": "Protokol ze zvláštního přezkumného jednání",
    "570": "Předložení přihlášky NS",
    "571": "Předložení přihlášky VS",
    "572": "Usnesení o nepřipuštění změny v osobě věřitele",
    "573": "Usnesení o vrácení zálohy na insolvenční řízení",
    "574": "Usnesení o vydání/vyplacení zálohy na náklady řízení správce",
    "576": "Vrácení přihlášky",
    "577": "Vrácení přihlášky soudu I.stupně",
    "578": "Výzva likvidátorovi",
    "579": "Zapůjčení přihlášky",
    "580": "Záznam o vydání",
    "581": "Zpětvzetí přihlášené pohledávky",
    "582": "Žádost insolvenčního správce",
    "583": "Žádost o prodloužení lhůty",
    "584": "Usnesení o vzetí na vědomí částečného zpětvzetí přihlášky",
    "585": "Předvolání k jednání",
    "586": "Usnesení o zamítnutí žaloby",
    "587": "Vykonatelnost",
    "588": "Zpětvzetí",
    "591": "Rozhodnutí z incidenčního sporu",
    "592": "Usnesení o část. nepřihlížení a odmítnutí přihlášky",
    "593": "Usnesení o část. odmítnutí přihlášky",
    "594": "Usnesení o část. ukončení účasti věřitele v insol. řízení",
    "595": "Usnesení o nepřihlížení a odmítnutí přihlášky",
    "596": "Usnesení o část.změně v osobě věřitele",
    "597": "Směnka",
    "598": "Návrh na určení lhůty",
    "599": "Zpráva o mimořádných splátkách dle § 412 odst. 1 písm. b)",
    "600": "Úřad práce - uspokojení mzdových nároků",
    "601": "Výzva na doplnění dovolání",
    "602": "Usnesení o odmítnutí jednoho z insolvenčních návrhů",
    "603": "Usnesení o zamítnutí jednoho z insolvenčních návrhů",
    "605": "Usnesení o změně splátkového kalendáře",
    "606": "Sdělení insolvenčního správce",
    "607": "Vyřízení reklamace",
    "608": "Konečná zpráva  - doplnění",
    "609": "Dotaz na CEO",
    "610": "Usnesení o ustanovení odděleného správce",
    "611": "Usnesení o zproštění odděleného správce",
    "612": "Zpětvzetí popření pohledávky dlužníkem",
    "613": "Usnesení o ustanovení opatrovníka pro insolvenční řízení",
    "614": "Usnesení o ustanovení opatrovníka pro doručování",
    "615": "Pokyn účtárně k vymáhání",
    "616": "Návrh na ustanovení předběžného správce",
    "617": "Zaslání rozhodnutí s doložkou právní moci",
    "618": "Záznam o složení",
    "619": "Usnesení o zrušení oddlužení z důvodu úmrtí dlužníka",
    "621": "Usnesení o spojení věci k společnému projednávání",
    "622": "Oddělení spojené věci",
    "624": "Rozhodnutí soudu o určení procesní lhůty",
    "625": "Zasílání údajů o změně osoby věřitele v přihlášce",
    "627": "Převzetí vyžádaného spisu",
    "628": "Zaslání rozhodnutí dovolacího soudu",
    "630": "Usnesení o schválení zprávy o reorganizačním plánu",
    "631": "Záznam o složení jistoty",
    "633": "Popření pohledávky přihlášeným věřitelem"
}
